#ifndef AMMO_REMOVER_VERSION_INCLUDED
#define AMMO_REMOVER_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define AMMO_REMOVER_VERSION_MAJOR  1
#define AMMO_REMOVER_VERSION_MINOR  1
#define AMMO_REMOVER_VERSION_PATCH  0
#define AMMO_REMOVER_VERSION_BETA   0

#define AMMO_REMOVER_VERSION	MAKE_STR(AMMO_REMOVER_VERSION_MAJOR) "." MAKE_STR(AMMO_REMOVER_VERSION_MINOR) \
	"." MAKE_STR(AMMO_REMOVER_VERSION_PATCH) "." MAKE_STR(AMMO_REMOVER_VERSION_BETA)

#endif
