#pragma once

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define RUNTIME_COMPATIBILITY RUNTIME_VERSION_1_10_984

#define AMMO_REMOVER_VERSION_MAJOR  1
#define AMMO_REMOVER_VERSION_MINOR  2
#define AMMO_REMOVER_VERSION_PATCH  1
#define AMMO_REMOVER_VERSION_BETA   0

#define AMMO_REMOVER_VERSION		MAKE_STR(AMMO_REMOVER_VERSION_MAJOR) "." MAKE_STR(AMMO_REMOVER_VERSION_MINOR) \
	"." MAKE_STR(AMMO_REMOVER_VERSION_PATCH) "." MAKE_STR(AMMO_REMOVER_VERSION_BETA)

#define AMMO_REMOVER_VERSION_INT	((AMMO_REMOVER_VERSION_MAJOR * 1000) + (AMMO_REMOVER_VERSION_MINOR * 100) \
	+ (AMMO_REMOVER_VERSION_PATCH * 10) + AMMO_REMOVER_VERSION_BETA)
