#pragma once

// Need both for some reason
#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define RUNTIME_COMPATIBILITY RUNTIME_VERSION_1_10_984

#define AR_VERSION_MAJOR 1
#define AR_VERSION_MINOR 2
#define AR_VERSION_PATCH 2
#define AR_VERSION_BETA  0

#define AR_VERSION_STR	MAKE_STR(AR_VERSION_MAJOR) "." MAKE_STR(AR_VERSION_MINOR) \
	"." MAKE_STR(AR_VERSION_PATCH) "." MAKE_STR(AR_VERSION_BETA)

#define AR_VERSION_INT	((AR_VERSION_MAJOR * 1000) + (AR_VERSION_MINOR * 100) \
	+ (AR_VERSION_PATCH * 10) + AR_VERSION_BETA)
